collections:
  - name: amazon.aws
    version: ">=10.0.0"
  - name: ansible.posix
    version: ">=2.0.0"
  - name: ansible.windows
    version: ">=3.0.0"
  - name: awx.awx
    version: ">=24.6.1"
  - name: azure.azcollection
    version: ">=3.10.0"
  - name: community.windows
    version: ">=3.0.0"
  - name: community.vmware
    version: ">=5.8.0"
  - name: vmware.vmware
    version: ">=2.5.0"
  - name: kubernetes.core
    version: ">=6.0.0"
  - name: google.cloud
    version: ">=1.10.0"
  - name: openstack.cloud
    version: ">=2.2.0"
  - name: ovirt.ovirt
    version: ">=3.2.0"
  - name: theforeman.foreman
    version: ">=5.6.0"
